{
  parserClass="io.toolisticon.plugins.jenkinsfile.parser.JenkinsParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Jenkins"
  psiImplClassSuffix="Impl"
  psiPackage="io.toolisticon.plugins.jenkinsfile.psi"
  psiImplPackage="io.toolisticon.plugins.jenkinsfile.psi.impl"

  elementTypeHolderClass="io.toolisticon.plugins.jenkinsfile.psi.JenkinsTypes"
  elementTypeClass="io.toolisticon.plugins.jenkinsfile.psi.JenkinsElementType"
  tokenTypeClass="io.toolisticon.plugins.jenkinsfile.psi.JenkinsTokenType"
}

jenkinsFile ::= item_*

private item_ ::= (step|CRLF|COMMENT)

step ::= (STEP_KEY PARAMETER) | STEP_KEY
